baseURL = "https://slc-hugo.netlify.app/"
languageCode = 'fr'
title = 'Syndicat du Logement et de la Consommation'
defaultContentLanguage = "fr"
hasCJKLanguage = false

theme = "tranquilpeak"

pagerSize  = 10
canonifyURLs = true
enableInlineShortcodes = true

[menu]

  [[menu.main]]
    
	
