baseURL = "https://slc-hugo.netlify.app/"
languageCode = 'fr'
title = 'Syndicat du Logement et de la Consommation'
defaultContentLanguage = "fr"
hasCJKLanguage = false

theme = "tranquilpeak"
canonifyURLs = true
enableInlineShortcodes = true

[pagination]
  pagerSize = 10

[params]
  author = "SLC"
  subtitle = "Site officiel du Syndicat du Logement et de la Consommation"
  description = "Association de défense des locataires"
  keywords = ["syndicat", "logement", "consommation", "association"]
  since = 1977
  enableSidebar = true
