baseURL = "https://slc-hugo.netlify.app/"
languageCode = 'fr'
title = 'Syndicat du Logement et de la Consommation'
defaultContentLanguage = "fr"

theme = "mainroad"
disableKinds = ["taxonomy"]

[Params.style.vars]
  highlightColor = "#4088b8"         # Couleur principale (bleu par défaut)

[Params.logo]
  image = "uploads/logo.jpg" # Logo image. Path relative to "static"
  subtitle = "Locataires, défendez vos droits avec le SLC-CSF !" # Logo subtitle
