backend:
  name: git-gateway
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth
  site_id: 1b5112af-e4d3-4fb5-b454-edb526c52b40

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }