backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:

  - name: "menu_pages"
    label: "Pages Menu Principal"
    folder: "content/menu"
    create: true
    slug: "{{slug}}"
    sortable_fields: ["weight", "title"] # Ajout des champs triables
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Poids (ordre dans le menu)", name: "weight", widget: "number", default: 10 }
      - { label: "Contenu", name: "body", widget: "markdown" }


  - name: "postes"
    label: "Articles"
    folder: "content/post"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Contenu", name: "body", widget: "markdown" }

  - name: "footer_pages"
    label: "Pages Footer"
    folder: "content/footer"
    create: true
    slug: "{{slug}}"
    sortable_fields: ["weight", "title"] # Ajout des champs triables
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Poids (ordre dans le footer)", name: "weight", widget: "number", default: 10 }
      - { label: "Contenu", name: "body", widget: "markdown" }
