backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/page"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Menu", name: "menu", widget: "list", pattern: ['main', "footer",""] }
      - { label: "Poids (ordre dans le menu)", name: "weight", widget: "number", default: 10 }
      - { label: "Contenu", name: "body", widget: "markdown" }

  - name: "postes"
    label: "Articles"
    folder: "content/post"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Contenu", name: "body", widget: "markdown" }
