backend:
  name: github
  repo: hugospinat/slc-hugo
  branch: main
  auth_scope: repo
  auth_endpoint: https://authenticating-git-user.vercel.app/api/auth

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Articles"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Contenu", name: "body", widget: "markdown" }